#!/bin/bash
# Example script showing how to use the Environment Manager

echo "SecondBrain Portable Environment Manager Example"
echo "=============================================="
echo ""
echo "To set up the Environment Manager anywhere:"
echo ""
echo "1. Activate the environment (do this first):"
echo "   source ./activate-env.sh"
echo ""
echo "2. Store your API keys (examples):"
echo "   sb-encrypt OPENAI_API_KEY 'your-api-key-here'"
echo "   sb-encrypt CLAUDE_API_KEY 'your-api-key-here'"
echo "   sb-encrypt MISTRAL_API_KEY 'your-api-key-here'"
echo ""
echo "3. Load your environment:"
echo "   sb-env"
echo ""
echo "4. List all stored keys:"
echo "   sb-list"
echo ""
echo "Your encryption key is stored in .secretstore/README.md"
echo "Make sure to keep a backup of this key in a secure location!"
