/Volumes/Envoy/SecondBrain/startup/cli_session_logger.js
...
        this._logToFile('SESSION_END', 'Failed to end session in Notion: Missing database ID or session not initialized');
...
        this._logToFile('COMPACTION', 'Failed to handle compaction in Notion: Missing database ID or session not initialized');
...
