

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deer-flow-backend
    ports:
      - "8000:8000"
    env_file:
      - ../secondbrain_api_keys.env
    environment:
      NEXT_PUBLIC_API_URL: "http://host.docker.internal:8000"
    # The conf.yaml volume mount is optional if conf.yaml.example is used
    # volumes:
    #   - ./conf.yaml:/app/conf.yaml
    restart: unless-stopped
    networks:
      - deer-flow-network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
    container_name: deer-flow-frontend
    ports:
      - "3000:3000"
    env_file:
      - ../secondbrain_api_keys.env
    environment:
      NEXT_PUBLIC_API_URL: "http://host.docker.internal:8000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - deer-flow-network

networks:
  deer-flow-network:
    driver: bridge